/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuBot.frame;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import javax.imageio.ImageIO;
import sudokuBot.SudokuRobot;

/**
 *
 * @author Danny
 */
public class FrameMain extends javax.swing.JFrame {
    Dimension screenSize;
    Dimension frameSize;
    SudokuRobot walle;
    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize=new Dimension ((int)screenSize.getWidth()/5,(int)screenSize.getHeight()/3);
        try{
            walle=new SudokuRobot(screenSize);
            initComponents();
        }catch(AWTException e){
            e.printStackTrace();
        }
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        pensamientoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_panel = new javax.swing.JTextPane();
        getBoard_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Bot 1.0");
        setAlwaysOnTop(true);
        setLocation(new Point(screenSize.width-frameSize.width,screenSize.height-frameSize.height)

        );
        setPreferredSize(frameSize);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(146, 27, 27));
        jPanel1.setLayout(null);

        botonInicio.setText("Inicio");
        botonInicio.setToolTipText("pues haga click para iniciar el robot");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(botonInicio);
        botonInicio.setBounds(200, 120, 70, 50);

        pensamientoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pensamientoLabel.setForeground(new java.awt.Color(255, 255, 255));
        pensamientoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pensamientoLabel.setText("EN ESPERA");
        jPanel1.add(pensamientoLabel);
        pensamientoLabel.setBounds(200, 70, 140, 40);

        jButton1.setText("test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 240, 70, 23);

        text_panel.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jScrollPane2.setViewportView(text_panel);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 180, 190);

        getBoard_button.setText("Tablero");
        getBoard_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBoard_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(getBoard_button);
        getBoard_button.setBounds(200, 180, 69, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        walle.vistaInicial();
        pensamientoLabel.setText(walle.focus(5)?"Enfocado":"No enfocado :(");
        text_panel.setText(text_panel.getText()+"\n"+walle.printEsquinas());
    }//GEN-LAST:event_botonInicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        walle.move(walle.esquinaInfDer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getBoard_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBoard_buttonActionPerformed
        if(walle.buildBoard()){
            text_panel.setText(text_panel.getText()+"\n"+walle.gimmeTheFuckingBoard());
        }
        
        
    }//GEN-LAST:event_getBoard_buttonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton getBoard_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pensamientoLabel;
    private javax.swing.JTextPane text_panel;
    // End of variables declaration//GEN-END:variables
}
